# Generated by Django 5.1.6 on 2025-09-19 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='es_administrador',
        ),
        migrations.AddField(
            model_name='user',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='nombre',
            field=models.CharField(default='Sin nombre', max_length=50),
        ),
    ]
