# Generated by Django 5.2.5 on 2025-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="es_administrador",
        ),
        migrations.AddField(
            model_name="user",
            name="apellido",
            field=models.CharField(default="", max_length=150),
        ),
        migrations.AddField(
            model_name="user",
            name="nombre",
            field=models.CharField(default="", max_length=50),
        ),
    ]
