# Generated by Django 5.1.6 on 2025-09-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('admin', 'Administrador')], default='cliente', editable=False, max_length=50),
        ),
    ]
