# Generated by Django 5.2.5 on 2025-10-06 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_user_apellido_alter_user_nombre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
