# Generated by Django 5.2.5 on 2025-09-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reserva",
            name="personas",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
