# Generated by Django 5.1.6 on 2025-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reserva_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='capacidad',
            field=models.IntegerField(default=6),
        ),
    ]
